apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fastapi
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: {{ .Values.fastapi.nodePort }}
  selector:
    app: {{ .Release.Name }}-fastapi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-fastapi
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-fastapi
  replicas: {{ .Values.fastapi.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-fastapi
    spec:
      containers:
        - name: fastapi
          image: {{ .Values.fastapi.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-fastapi-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-fastapi
  minReplicas: {{ .Values.fastapi.hpa.minReplicas }}
  maxReplicas: {{ .Values.fastapi.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.fastapi.hpa.targetCPUUtilizationPercentage }}
