apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pgadmin
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: {{ .Values.pgadmin.nodePort }}
  selector:
    app: {{ .Release.Name }}-pgadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pgadmin
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-pgadmin
  replicas: {{ .Values.pgadmin.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-pgadmin
    spec:
      containers:
        - name: pgadmin
          image: {{ .Values.pgadmin.image }}
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: {{ .Values.pgadmin.email }}
            - name: PGADMIN_DEFAULT_PASSWORD
              value: {{ .Values.pgadmin.password }}
